adam_beta1: 0.9
adam_beta2: 0.999
adam_epsilon: 1.0e-08
adam_weight_decay: 0.01
algorithm_type: dpmsolver++
beta_scheduler: scaled_linear
channel_attn: true
character_input: true
ckpt_dir: ./ckpt
ckpt_interval: 40000
content_encoder_downsample_size: 3
content_image_size: !!python/tuple
- 96
- 96
content_start_channel: 64
correcting_x0_fn: null
data_root: null
debug: true
device: cuda:0
drop_prob: 0.1
end_line: null
excel_file: SinoNom_Similar_Dic_v2.xlsx
experience_name: fontdiffuer_training
font_dir: null
font_paths:
- HanaMinA.otf
- HanaMinB.otf
- HanaMinC.otf
- NomNaTong-Regular.ttf
gradient_accumulation_steps: 1
guidance_scale: 7.5
guidance_type: classifier-free
learning_rate: 0.0001
local_rank: -1
log_interval: 100
logging_dir: logs
lr_scheduler: linear
lr_warmup_steps: 10000
max_grad_norm: 1.0
max_rows: null
max_train_steps: 440000
method: multistep
mixed_precision: 'no'
mode: refinement
model_type: noise
nce_layers: 0,1,2,3
num_inference_steps: 20
num_neg: 16
offset_coefficient: 0.5
order: 2
output_base_dir: ./font_generations
output_dir: null
perceptual_coefficient: 0.01
phase_1_ckpt_dir: null
phase_2: false
report_to: tensorboard
resolution: 96
sc_coefficient: 0.01
scale_lr: false
scr_ckpt_path: null
scr_image_size: 96
seed: 123
skip_input_char: false
skip_type: time_uniform
start_line: null
style_image_path: font_diffusion/data_examples/sampling/example_style.jpg
style_image_size: !!python/tuple
- 96
- 96
style_start_channel: 64
t_end: null
t_start: null
temperature: 0.07
train_batch_size: 4
ttf_path:
- HanaMinA.otf
- HanaMinB.otf
- HanaMinC.otf
- NomNaTong-Regular.ttf
unet_channels: !!python/tuple
- 64
- 128
- 256
- 512
